<!DOCTYPE html>
<html lang="en">

<body>
    <h2>Login</h2>
    <!-- form generated by codeigniter -->

    <!-- home route -->
    <?php foreach ($home as $item) : ?>
        <a href="<?= $item['url'] ?>">
            <?= $item['title'] ?>
        </a>
    <?php endforeach; ?>
</body>

</html>